ALTER TABLE users DROP COLUMN IF EXISTS phone;

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS legal_name    TEXT         NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone         TEXT         NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_line1 TEXT         NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS subdistrict   TEXT         NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS district      TEXT         NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS province      TEXT         NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS postal_code   VARCHAR(5)   NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS branch_number VARCHAR(5)   NOT NULL DEFAULT '00000';
