// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteSpaceAvailability = `-- name: DeleteSpaceAvailability :exec
DELETE FROM space_availability
WHERE space_id = $1
`

func (q *Queries) DeleteSpaceAvailability(ctx context.Context, spaceID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceAvailability, spaceID)
	return err
}

const getSpaceAvailability = `-- name: GetSpaceAvailability :many
SELECT id, space_id, day_of_week, open_time, close_time FROM space_availability
WHERE space_id = $1
ORDER BY day_of_week
`

func (q *Queries) GetSpaceAvailability(ctx context.Context, spaceID uuid.UUID) ([]SpaceAvailability, error) {
	rows, err := q.db.QueryContext(ctx, getSpaceAvailability, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceAvailability
	for rows.Next() {
		var i SpaceAvailability
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.DayOfWeek,
			&i.OpenTime,
			&i.CloseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSpaceAvailability = `-- name: UpsertSpaceAvailability :one
INSERT INTO space_availability (space_id, day_of_week, open_time, close_time)
VALUES ($1, $2, $3, $4)
ON CONFLICT (space_id, day_of_week) DO UPDATE SET
  open_time  = EXCLUDED.open_time,
  close_time = EXCLUDED.close_time
RETURNING id, space_id, day_of_week, open_time, close_time
`

type UpsertSpaceAvailabilityParams struct {
	SpaceID   uuid.UUID `json:"space_id"`
	DayOfWeek int16     `json:"day_of_week"`
	OpenTime  string    `json:"open_time"`
	CloseTime string    `json:"close_time"`
}

func (q *Queries) UpsertSpaceAvailability(ctx context.Context, arg UpsertSpaceAvailabilityParams) (SpaceAvailability, error) {
	row := q.db.QueryRowContext(ctx, upsertSpaceAvailability,
		arg.SpaceID,
		arg.DayOfWeek,
		arg.OpenTime,
		arg.CloseTime,
	)
	var i SpaceAvailability
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.DayOfWeek,
		&i.OpenTime,
		&i.CloseTime,
	)
	return i, err
}
