// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkCompleteConfirmedBookings = `-- name: BulkCompleteConfirmedBookings :many
UPDATE bookings
SET status = 'completed', updated_at = NOW()
WHERE status   = 'confirmed'
  AND end_time <= NOW()
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code
`

func (q *Queries) BulkCompleteConfirmedBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, bulkCompleteConfirmedBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkExpirePendingBookings = `-- name: BulkExpirePendingBookings :many
UPDATE bookings
SET status = 'cancelled', cancel_reason = 'expired', updated_at = NOW()
WHERE status     = 'pending'
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code
`

func (q *Queries) BulkExpirePendingBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, bulkExpirePendingBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelOverlappingPendingBookings = `-- name: CancelOverlappingPendingBookings :many
UPDATE bookings
SET status = 'cancelled', cancel_reason = 'auto_cancelled', updated_at = NOW()
WHERE renter_id  = $1
  AND id        != $2
  AND status     IN ('pending', 'awaiting_payment')
  AND start_time < $4
  AND end_time   > $3
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code
`

type CancelOverlappingPendingBookingsParams struct {
	RenterID  uuid.UUID `json:"renter_id"`
	ID        uuid.UUID `json:"id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) CancelOverlappingPendingBookings(ctx context.Context, arg CancelOverlappingPendingBookingsParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, cancelOverlappingPendingBookings,
		arg.RenterID,
		arg.ID,
		arg.EndTime,
		arg.StartTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkOverlappingBookings = `-- name: CheckOverlappingBookings :one
SELECT COUNT(*) FROM bookings
WHERE space_id   = $1
  AND status     IN ('pending', 'awaiting_payment', 'payment_review', 'confirmed')
  AND start_time < $3
  AND end_time   > $2
`

type CheckOverlappingBookingsParams struct {
	SpaceID   uuid.UUID `json:"space_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) CheckOverlappingBookings(ctx context.Context, arg CheckOverlappingBookingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkOverlappingBookings, arg.SpaceID, arg.EndTime, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveBookingsByRenterForSpace = `-- name: CountActiveBookingsByRenterForSpace :one
SELECT COUNT(*) FROM bookings
WHERE renter_id = $1
  AND space_id  = $2
  AND status    IN ('pending', 'awaiting_payment', 'payment_review', 'confirmed')
`

type CountActiveBookingsByRenterForSpaceParams struct {
	RenterID uuid.UUID `json:"renter_id"`
	SpaceID  uuid.UUID `json:"space_id"`
}

func (q *Queries) CountActiveBookingsByRenterForSpace(ctx context.Context, arg CountActiveBookingsByRenterForSpaceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBookingsByRenterForSpace, arg.RenterID, arg.SpaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsBySpace = `-- name: CountBookingsBySpace :one
SELECT COUNT(*) FROM bookings WHERE space_id = $1
`

func (q *Queries) CountBookingsBySpace(ctx context.Context, spaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookingsBySpace, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingBookingsByRenter = `-- name: CountPendingBookingsByRenter :one
SELECT COUNT(*) FROM bookings
WHERE renter_id = $1
  AND status    IN ('pending', 'awaiting_payment', 'payment_review')
`

func (q *Queries) CountPendingBookingsByRenter(ctx context.Context, renterID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingBookingsByRenter, renterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (space_id, renter_id, start_time, end_time, total_price, platform_fee, headcount, notes, expires_at, ref_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code
`

type CreateBookingParams struct {
	SpaceID     uuid.UUID      `json:"space_id"`
	RenterID    uuid.UUID      `json:"renter_id"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	TotalPrice  int32          `json:"total_price"`
	PlatformFee int32          `json:"platform_fee"`
	Headcount   sql.NullInt32  `json:"headcount"`
	Notes       sql.NullString `json:"notes"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	RefCode     string         `json:"ref_code"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.SpaceID,
		arg.RenterID,
		arg.StartTime,
		arg.EndTime,
		arg.TotalPrice,
		arg.PlatformFee,
		arg.Headcount,
		arg.Notes,
		arg.ExpiresAt,
		arg.RefCode,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Headcount,
		&i.Notes,
		&i.ExpiresAt,
		&i.CancelReason,
		&i.RefundStatus,
		&i.ProcessExpiresAt,
		&i.SlipUrl,
		&i.RefCode,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Headcount,
		&i.Notes,
		&i.ExpiresAt,
		&i.CancelReason,
		&i.RefundStatus,
		&i.ProcessExpiresAt,
		&i.SlipUrl,
		&i.RefCode,
	)
	return i, err
}

const listActiveBookingsInRange = `-- name: ListActiveBookingsInRange :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code FROM bookings
WHERE space_id   = $1
  AND status     IN ('pending', 'awaiting_payment', 'payment_review', 'confirmed')
  AND start_time < $3
  AND end_time   > $2
ORDER BY start_time ASC
`

type ListActiveBookingsInRangeParams struct {
	SpaceID   uuid.UUID `json:"space_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) ListActiveBookingsInRange(ctx context.Context, arg ListActiveBookingsInRangeParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBookingsInRange, arg.SpaceID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByOwner = `-- name: ListBookingsByOwner :many
SELECT b.id, b.space_id, b.renter_id, b.start_time, b.end_time, b.total_price, b.platform_fee, b.status, b.created_at, b.updated_at, b.headcount, b.notes, b.expires_at, b.cancel_reason, b.refund_status, b.process_expires_at, b.slip_url, b.ref_code FROM bookings b
JOIN spaces s ON s.id = b.space_id
WHERE s.owner_id = $1
ORDER BY b.start_time DESC
`

func (q *Queries) ListBookingsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByOwnerEnriched = `-- name: ListBookingsByOwnerEnriched :many
SELECT b.id, b.space_id, b.renter_id, b.start_time, b.end_time, b.total_price, b.platform_fee, b.status, b.created_at, b.updated_at, b.headcount, b.notes, b.expires_at, b.cancel_reason, b.refund_status, b.process_expires_at, b.slip_url, b.ref_code, s.name AS space_name, s.location AS space_location, s.images AS space_images
FROM bookings b
JOIN spaces s ON s.id = b.space_id
WHERE s.owner_id = $1
ORDER BY b.start_time DESC
`

type ListBookingsByOwnerEnrichedRow struct {
	ID               uuid.UUID      `json:"id"`
	SpaceID          uuid.UUID      `json:"space_id"`
	RenterID         uuid.UUID      `json:"renter_id"`
	StartTime        time.Time      `json:"start_time"`
	EndTime          time.Time      `json:"end_time"`
	TotalPrice       int32          `json:"total_price"`
	PlatformFee      int32          `json:"platform_fee"`
	Status           BookingStatus  `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	Headcount        sql.NullInt32  `json:"headcount"`
	Notes            sql.NullString `json:"notes"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	CancelReason     sql.NullString `json:"cancel_reason"`
	RefundStatus     sql.NullString `json:"refund_status"`
	ProcessExpiresAt sql.NullTime   `json:"process_expires_at"`
	SlipUrl          sql.NullString `json:"slip_url"`
	RefCode          string         `json:"ref_code"`
	SpaceName        string         `json:"space_name"`
	SpaceLocation    string         `json:"space_location"`
	SpaceImages      []string       `json:"space_images"`
}

func (q *Queries) ListBookingsByOwnerEnriched(ctx context.Context, ownerID uuid.UUID) ([]ListBookingsByOwnerEnrichedRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByOwnerEnriched, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByOwnerEnrichedRow
	for rows.Next() {
		var i ListBookingsByOwnerEnrichedRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
			&i.SpaceName,
			&i.SpaceLocation,
			pq.Array(&i.SpaceImages),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByRenter = `-- name: ListBookingsByRenter :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code FROM bookings
WHERE renter_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListBookingsByRenter(ctx context.Context, renterID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByRenter, renterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByRenterEnriched = `-- name: ListBookingsByRenterEnriched :many
SELECT b.id, b.space_id, b.renter_id, b.start_time, b.end_time, b.total_price, b.platform_fee, b.status, b.created_at, b.updated_at, b.headcount, b.notes, b.expires_at, b.cancel_reason, b.refund_status, b.process_expires_at, b.slip_url, b.ref_code, s.name AS space_name, s.location AS space_location, s.images AS space_images
FROM bookings b
JOIN spaces s ON s.id = b.space_id
WHERE b.renter_id = $1
ORDER BY b.start_time DESC
`

type ListBookingsByRenterEnrichedRow struct {
	ID               uuid.UUID      `json:"id"`
	SpaceID          uuid.UUID      `json:"space_id"`
	RenterID         uuid.UUID      `json:"renter_id"`
	StartTime        time.Time      `json:"start_time"`
	EndTime          time.Time      `json:"end_time"`
	TotalPrice       int32          `json:"total_price"`
	PlatformFee      int32          `json:"platform_fee"`
	Status           BookingStatus  `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	Headcount        sql.NullInt32  `json:"headcount"`
	Notes            sql.NullString `json:"notes"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	CancelReason     sql.NullString `json:"cancel_reason"`
	RefundStatus     sql.NullString `json:"refund_status"`
	ProcessExpiresAt sql.NullTime   `json:"process_expires_at"`
	SlipUrl          sql.NullString `json:"slip_url"`
	RefCode          string         `json:"ref_code"`
	SpaceName        string         `json:"space_name"`
	SpaceLocation    string         `json:"space_location"`
	SpaceImages      []string       `json:"space_images"`
}

func (q *Queries) ListBookingsByRenterEnriched(ctx context.Context, renterID uuid.UUID) ([]ListBookingsByRenterEnrichedRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByRenterEnriched, renterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByRenterEnrichedRow
	for rows.Next() {
		var i ListBookingsByRenterEnrichedRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
			&i.SpaceName,
			&i.SpaceLocation,
			pq.Array(&i.SpaceImages),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsBySpace = `-- name: ListBookingsBySpace :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code FROM bookings
WHERE space_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListBookingsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsBySpacePaginated = `-- name: ListBookingsBySpacePaginated :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code FROM bookings
WHERE space_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListBookingsBySpacePaginatedParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListBookingsBySpacePaginated(ctx context.Context, arg ListBookingsBySpacePaginatedParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsBySpacePaginated, arg.SpaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentPendingBookings = `-- name: ListPaymentPendingBookings :many
SELECT b.id, b.space_id, b.renter_id, b.start_time, b.end_time, b.total_price, b.platform_fee, b.status, b.created_at, b.updated_at, b.headcount, b.notes, b.expires_at, b.cancel_reason, b.refund_status, b.process_expires_at, b.slip_url, b.ref_code, s.name AS space_name, s.location AS space_location, s.images AS space_images, p.profile_name AS renter_name
FROM bookings b
JOIN spaces s ON s.id = b.space_id
JOIN profiles p ON p.id = b.renter_id
WHERE b.status = 'payment_review'
ORDER BY b.created_at ASC
`

type ListPaymentPendingBookingsRow struct {
	ID               uuid.UUID      `json:"id"`
	SpaceID          uuid.UUID      `json:"space_id"`
	RenterID         uuid.UUID      `json:"renter_id"`
	StartTime        time.Time      `json:"start_time"`
	EndTime          time.Time      `json:"end_time"`
	TotalPrice       int32          `json:"total_price"`
	PlatformFee      int32          `json:"platform_fee"`
	Status           BookingStatus  `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	Headcount        sql.NullInt32  `json:"headcount"`
	Notes            sql.NullString `json:"notes"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	CancelReason     sql.NullString `json:"cancel_reason"`
	RefundStatus     sql.NullString `json:"refund_status"`
	ProcessExpiresAt sql.NullTime   `json:"process_expires_at"`
	SlipUrl          sql.NullString `json:"slip_url"`
	RefCode          string         `json:"ref_code"`
	SpaceName        string         `json:"space_name"`
	SpaceLocation    string         `json:"space_location"`
	SpaceImages      []string       `json:"space_images"`
	RenterName       string         `json:"renter_name"`
}

func (q *Queries) ListPaymentPendingBookings(ctx context.Context) ([]ListPaymentPendingBookingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentPendingBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentPendingBookingsRow
	for rows.Next() {
		var i ListPaymentPendingBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
			&i.CancelReason,
			&i.RefundStatus,
			&i.ProcessExpiresAt,
			&i.SlipUrl,
			&i.RefCode,
			&i.SpaceName,
			&i.SpaceLocation,
			pq.Array(&i.SpaceImages),
			&i.RenterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET status = $2, cancel_reason = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at, cancel_reason, refund_status, process_expires_at, slip_url, ref_code
`

type UpdateBookingStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       BookingStatus  `json:"status"`
	CancelReason sql.NullString `json:"cancel_reason"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingStatus, arg.ID, arg.Status, arg.CancelReason)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Headcount,
		&i.Notes,
		&i.ExpiresAt,
		&i.CancelReason,
		&i.RefundStatus,
		&i.ProcessExpiresAt,
		&i.SlipUrl,
		&i.RefCode,
	)
	return i, err
}
