// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkOverlappingBookings = `-- name: CheckOverlappingBookings :one
SELECT COUNT(*) FROM bookings
WHERE space_id   = $1
  AND status     IN ('pending', 'confirmed')
  AND start_time < $3
  AND end_time   > $2
`

type CheckOverlappingBookingsParams struct {
	SpaceID   uuid.UUID `json:"space_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) CheckOverlappingBookings(ctx context.Context, arg CheckOverlappingBookingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkOverlappingBookings, arg.SpaceID, arg.EndTime, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (space_id, renter_id, start_time, end_time, total_price, platform_fee)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at
`

type CreateBookingParams struct {
	SpaceID     uuid.UUID `json:"space_id"`
	RenterID    uuid.UUID `json:"renter_id"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	TotalPrice  int32     `json:"total_price"`
	PlatformFee int32     `json:"platform_fee"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.SpaceID,
		arg.RenterID,
		arg.StartTime,
		arg.EndTime,
		arg.TotalPrice,
		arg.PlatformFee,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByRenter = `-- name: ListBookingsByRenter :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at FROM bookings
WHERE renter_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListBookingsByRenter(ctx context.Context, renterID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByRenter, renterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsBySpace = `-- name: ListBookingsBySpace :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at FROM bookings
WHERE space_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListBookingsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status BookingStatus `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
