// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const bulkCompleteConfirmedBookings = `-- name: BulkCompleteConfirmedBookings :many
UPDATE bookings
SET status = 'completed', updated_at = NOW()
WHERE status   = 'confirmed'
  AND end_time <= NOW()
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at
`

func (q *Queries) BulkCompleteConfirmedBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, bulkCompleteConfirmedBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkExpirePendingBookings = `-- name: BulkExpirePendingBookings :many
UPDATE bookings
SET status = 'cancelled', updated_at = NOW()
WHERE status     = 'pending'
  AND expires_at IS NOT NULL
  AND expires_at <= NOW()
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at
`

func (q *Queries) BulkExpirePendingBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, bulkExpirePendingBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelOverlappingPendingBookings = `-- name: CancelOverlappingPendingBookings :many
UPDATE bookings
SET status = 'cancelled', updated_at = NOW()
WHERE renter_id  = $1
  AND id        != $2
  AND status     = 'pending'
  AND start_time < $4
  AND end_time   > $3
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at
`

type CancelOverlappingPendingBookingsParams struct {
	RenterID  uuid.UUID `json:"renter_id"`
	ID        uuid.UUID `json:"id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) CancelOverlappingPendingBookings(ctx context.Context, arg CancelOverlappingPendingBookingsParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, cancelOverlappingPendingBookings,
		arg.RenterID,
		arg.ID,
		arg.EndTime,
		arg.StartTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkOverlappingBookings = `-- name: CheckOverlappingBookings :one
SELECT COUNT(*) FROM bookings
WHERE space_id   = $1
  AND status     IN ('pending', 'confirmed')
  AND start_time < $3
  AND end_time   > $2
`

type CheckOverlappingBookingsParams struct {
	SpaceID   uuid.UUID `json:"space_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) CheckOverlappingBookings(ctx context.Context, arg CheckOverlappingBookingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkOverlappingBookings, arg.SpaceID, arg.EndTime, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveBookingsByRenterForSpace = `-- name: CountActiveBookingsByRenterForSpace :one
SELECT COUNT(*) FROM bookings
WHERE renter_id = $1
  AND space_id  = $2
  AND status    IN ('pending', 'confirmed')
`

type CountActiveBookingsByRenterForSpaceParams struct {
	RenterID uuid.UUID `json:"renter_id"`
	SpaceID  uuid.UUID `json:"space_id"`
}

func (q *Queries) CountActiveBookingsByRenterForSpace(ctx context.Context, arg CountActiveBookingsByRenterForSpaceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBookingsByRenterForSpace, arg.RenterID, arg.SpaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsBySpace = `-- name: CountBookingsBySpace :one
SELECT COUNT(*) FROM bookings WHERE space_id = $1
`

func (q *Queries) CountBookingsBySpace(ctx context.Context, spaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookingsBySpace, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingBookingsByRenter = `-- name: CountPendingBookingsByRenter :one
SELECT COUNT(*) FROM bookings
WHERE renter_id = $1
  AND status    = 'pending'
`

func (q *Queries) CountPendingBookingsByRenter(ctx context.Context, renterID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingBookingsByRenter, renterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (space_id, renter_id, start_time, end_time, total_price, platform_fee, headcount, notes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at
`

type CreateBookingParams struct {
	SpaceID     uuid.UUID      `json:"space_id"`
	RenterID    uuid.UUID      `json:"renter_id"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	TotalPrice  int32          `json:"total_price"`
	PlatformFee int32          `json:"platform_fee"`
	Headcount   sql.NullInt32  `json:"headcount"`
	Notes       sql.NullString `json:"notes"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.SpaceID,
		arg.RenterID,
		arg.StartTime,
		arg.EndTime,
		arg.TotalPrice,
		arg.PlatformFee,
		arg.Headcount,
		arg.Notes,
		arg.ExpiresAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Headcount,
		&i.Notes,
		&i.ExpiresAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Headcount,
		&i.Notes,
		&i.ExpiresAt,
	)
	return i, err
}

const listBookingsByOwner = `-- name: ListBookingsByOwner :many
SELECT b.id, b.space_id, b.renter_id, b.start_time, b.end_time, b.total_price, b.platform_fee, b.status, b.created_at, b.updated_at, b.headcount, b.notes, b.expires_at FROM bookings b
JOIN spaces s ON s.id = b.space_id
WHERE s.owner_id = $1
ORDER BY b.start_time DESC
`

func (q *Queries) ListBookingsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByRenter = `-- name: ListBookingsByRenter :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at FROM bookings
WHERE renter_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListBookingsByRenter(ctx context.Context, renterID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsByRenter, renterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsBySpace = `-- name: ListBookingsBySpace :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at FROM bookings
WHERE space_id = $1
ORDER BY start_time DESC
`

func (q *Queries) ListBookingsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsBySpacePaginated = `-- name: ListBookingsBySpacePaginated :many
SELECT id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at FROM bookings
WHERE space_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListBookingsBySpacePaginatedParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListBookingsBySpacePaginated(ctx context.Context, arg ListBookingsBySpacePaginatedParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsBySpacePaginated, arg.SpaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.RenterID,
			&i.StartTime,
			&i.EndTime,
			&i.TotalPrice,
			&i.PlatformFee,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headcount,
			&i.Notes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, space_id, renter_id, start_time, end_time, total_price, platform_fee, status, created_at, updated_at, headcount, notes, expires_at
`

type UpdateBookingStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status BookingStatus `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.RenterID,
		&i.StartTime,
		&i.EndTime,
		&i.TotalPrice,
		&i.PlatformFee,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Headcount,
		&i.Notes,
		&i.ExpiresAt,
	)
	return i, err
}
