// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createBookingDocument = `-- name: CreateBookingDocument :one
INSERT INTO booking_documents (booking_id, doc_type, doc_number)
VALUES ($1, $2, $3)
ON CONFLICT (booking_id, doc_type) DO UPDATE
  SET doc_number = EXCLUDED.doc_number
RETURNING id, booking_id, doc_type, doc_number, issued_at
`

type CreateBookingDocumentParams struct {
	BookingID uuid.UUID `json:"booking_id"`
	DocType   string    `json:"doc_type"`
	DocNumber string    `json:"doc_number"`
}

func (q *Queries) CreateBookingDocument(ctx context.Context, arg CreateBookingDocumentParams) (BookingDocument, error) {
	row := q.db.QueryRowContext(ctx, createBookingDocument, arg.BookingID, arg.DocType, arg.DocNumber)
	var i BookingDocument
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.DocType,
		&i.DocNumber,
		&i.IssuedAt,
	)
	return i, err
}

const getBookingDocument = `-- name: GetBookingDocument :one
SELECT id, booking_id, doc_type, doc_number, issued_at FROM booking_documents
WHERE booking_id = $1 AND doc_type = $2
`

type GetBookingDocumentParams struct {
	BookingID uuid.UUID `json:"booking_id"`
	DocType   string    `json:"doc_type"`
}

func (q *Queries) GetBookingDocument(ctx context.Context, arg GetBookingDocumentParams) (BookingDocument, error) {
	row := q.db.QueryRowContext(ctx, getBookingDocument, arg.BookingID, arg.DocType)
	var i BookingDocument
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.DocType,
		&i.DocNumber,
		&i.IssuedAt,
	)
	return i, err
}

const listBookingDocuments = `-- name: ListBookingDocuments :many
SELECT id, booking_id, doc_type, doc_number, issued_at FROM booking_documents
WHERE booking_id = $1
ORDER BY issued_at ASC
`

func (q *Queries) ListBookingDocuments(ctx context.Context, bookingID uuid.UUID) ([]BookingDocument, error) {
	rows, err := q.db.QueryContext(ctx, listBookingDocuments, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingDocument
	for rows.Next() {
		var i BookingDocument
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.DocType,
			&i.DocNumber,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDocumentSequence = `-- name: NextDocumentSequence :one
INSERT INTO document_sequences (doc_type, year, next_seq)
VALUES ($1, $2, 2)
ON CONFLICT (doc_type, year) DO UPDATE
  SET next_seq = document_sequences.next_seq + 1
RETURNING next_seq - 1 AS seq
`

type NextDocumentSequenceParams struct {
	DocType string `json:"doc_type"`
	Year    int32  `json:"year"`
}

func (q *Queries) NextDocumentSequence(ctx context.Context, arg NextDocumentSequenceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextDocumentSequence, arg.DocType, arg.Year)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}
