// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BookingStatus string

const (
	BookingStatusPending   BookingStatus = "pending"
	BookingStatusConfirmed BookingStatus = "confirmed"
	BookingStatusCompleted BookingStatus = "completed"
	BookingStatusCancelled BookingStatus = "cancelled"
)

func (e *BookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingStatus(s)
	case string:
		*e = BookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingStatus: %T", src)
	}
	return nil
}

type NullBookingStatus struct {
	BookingStatus BookingStatus `json:"booking_status"`
	Valid         bool          `json:"valid"` // Valid is true if BookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingStatus), nil
}

type RenterType string

const (
	RenterTypeIndividual RenterType = "individual"
	RenterTypeCompany    RenterType = "company"
)

func (e *RenterType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RenterType(s)
	case string:
		*e = RenterType(s)
	default:
		return fmt.Errorf("unsupported scan type for RenterType: %T", src)
	}
	return nil
}

type NullRenterType struct {
	RenterType RenterType `json:"renter_type"`
	Valid      bool       `json:"valid"` // Valid is true if RenterType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRenterType) Scan(value interface{}) error {
	if value == nil {
		ns.RenterType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RenterType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRenterType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RenterType), nil
}

type SpaceCategory string

const (
	SpaceCategoryStudio  SpaceCategory = "Studio"
	SpaceCategoryOutdoor SpaceCategory = "Outdoor"
	SpaceCategoryLoft    SpaceCategory = "Loft"
	SpaceCategoryGarden  SpaceCategory = "Garden"
	SpaceCategoryOffice  SpaceCategory = "Office"
	SpaceCategoryCaf     SpaceCategory = "Café"
)

func (e *SpaceCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpaceCategory(s)
	case string:
		*e = SpaceCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for SpaceCategory: %T", src)
	}
	return nil
}

type NullSpaceCategory struct {
	SpaceCategory SpaceCategory `json:"space_category"`
	Valid         bool          `json:"valid"` // Valid is true if SpaceCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpaceCategory) Scan(value interface{}) error {
	if value == nil {
		ns.SpaceCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpaceCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpaceCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpaceCategory), nil
}

type UserRole string

const (
	UserRoleOwner  UserRole = "owner"
	UserRoleRenter UserRole = "renter"
	UserRoleBoth   UserRole = "both"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Booking struct {
	ID          uuid.UUID      `json:"id"`
	SpaceID     uuid.UUID      `json:"space_id"`
	RenterID    uuid.UUID      `json:"renter_id"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	TotalPrice  int32          `json:"total_price"`
	PlatformFee int32          `json:"platform_fee"`
	Status      BookingStatus  `json:"status"`
	RenterType  RenterType     `json:"renter_type"`
	CompanyName sql.NullString `json:"company_name"`
	TaxID       sql.NullString `json:"tax_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Space struct {
	ID          uuid.UUID     `json:"id"`
	OwnerID     uuid.UUID     `json:"owner_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Location    string        `json:"location"`
	Category    SpaceCategory `json:"category"`
	Images      []string      `json:"images"`
	HourlyRate  int32         `json:"hourly_rate"`
	DailyRate   int32         `json:"daily_rate"`
	MinHours    int32         `json:"min_hours"`
	Capacity    int32         `json:"capacity"`
	Amenities   []string      `json:"amenities"`
	IsActive    bool          `json:"is_active"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	Email           string         `json:"email"`
	PasswordHash    string         `json:"password_hash"`
	FullName        string         `json:"full_name"`
	Phone           sql.NullString `json:"phone"`
	Role            UserRole       `json:"role"`
	TaxID           sql.NullString `json:"tax_id"`
	IsJuristic      bool           `json:"is_juristic"`
	IsVatRegistered bool           `json:"is_vat_registered"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
