// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE profile_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, profileID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (profile_id, type, payload, booking_id)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, type, payload, read_at, created_at, superseded_at, booking_id
`

type CreateNotificationParams struct {
	ProfileID uuid.UUID       `json:"profile_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	BookingID uuid.NullUUID   `json:"booking_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ProfileID,
		arg.Type,
		arg.Payload,
		arg.BookingID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Type,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
		&i.SupersededAt,
		&i.BookingID,
	)
	return i, err
}

const listNotificationsByProfile = `-- name: ListNotificationsByProfile :many
SELECT id, profile_id, type, payload, read_at, created_at, superseded_at, booking_id FROM notifications
WHERE profile_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsByProfileParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListNotificationsByProfile(ctx context.Context, arg ListNotificationsByProfileParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByProfile, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Type,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
			&i.SupersededAt,
			&i.BookingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = NOW()
WHERE profile_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, profileID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = NOW()
WHERE id = $1 AND profile_id = $2
`

type MarkNotificationReadParams struct {
	ID        uuid.UUID `json:"id"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.ProfileID)
	return err
}

const supersedeNotificationsByBooking = `-- name: SupersedeNotificationsByBooking :exec
UPDATE notifications SET superseded_at = NOW()
WHERE booking_id = $1 AND superseded_at IS NULL
`

func (q *Queries) SupersedeNotificationsByBooking(ctx context.Context, bookingID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, supersedeNotificationsByBooking, bookingID)
	return err
}
