// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, role, profile_name, legal_name_th, legal_name_en, phone, address_line1, subdistrict, district, province, postal_code, branch_number, tax_id, is_juristic, is_vat_registered, line_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, user_id, role, profile_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id, legal_name_th, phone, address_line1, subdistrict, district, province, postal_code, branch_number, legal_name_en
`

type CreateProfileParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	Role            ProfileRole    `json:"role"`
	ProfileName     string         `json:"profile_name"`
	LegalNameTh     string         `json:"legal_name_th"`
	LegalNameEn     string         `json:"legal_name_en"`
	Phone           string         `json:"phone"`
	AddressLine1    string         `json:"address_line1"`
	Subdistrict     string         `json:"subdistrict"`
	District        string         `json:"district"`
	Province        string         `json:"province"`
	PostalCode      string         `json:"postal_code"`
	BranchNumber    string         `json:"branch_number"`
	TaxID           sql.NullString `json:"tax_id"`
	IsJuristic      bool           `json:"is_juristic"`
	IsVatRegistered bool           `json:"is_vat_registered"`
	LineID          sql.NullString `json:"line_id"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.UserID,
		arg.Role,
		arg.ProfileName,
		arg.LegalNameTh,
		arg.LegalNameEn,
		arg.Phone,
		arg.AddressLine1,
		arg.Subdistrict,
		arg.District,
		arg.Province,
		arg.PostalCode,
		arg.BranchNumber,
		arg.TaxID,
		arg.IsJuristic,
		arg.IsVatRegistered,
		arg.LineID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.ProfileName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
		&i.LegalNameTh,
		&i.Phone,
		&i.AddressLine1,
		&i.Subdistrict,
		&i.District,
		&i.Province,
		&i.PostalCode,
		&i.BranchNumber,
		&i.LegalNameEn,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, user_id, role, profile_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id, legal_name_th, phone, address_line1, subdistrict, district, province, postal_code, branch_number, legal_name_en FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.ProfileName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
		&i.LegalNameTh,
		&i.Phone,
		&i.AddressLine1,
		&i.Subdistrict,
		&i.District,
		&i.Province,
		&i.PostalCode,
		&i.BranchNumber,
		&i.LegalNameEn,
	)
	return i, err
}

const getProfileByUserAndRole = `-- name: GetProfileByUserAndRole :one
SELECT id, user_id, role, profile_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id, legal_name_th, phone, address_line1, subdistrict, district, province, postal_code, branch_number, legal_name_en FROM profiles WHERE user_id = $1 AND role = $2
`

type GetProfileByUserAndRoleParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Role   ProfileRole `json:"role"`
}

func (q *Queries) GetProfileByUserAndRole(ctx context.Context, arg GetProfileByUserAndRoleParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserAndRole, arg.UserID, arg.Role)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.ProfileName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
		&i.LegalNameTh,
		&i.Phone,
		&i.AddressLine1,
		&i.Subdistrict,
		&i.District,
		&i.Province,
		&i.PostalCode,
		&i.BranchNumber,
		&i.LegalNameEn,
	)
	return i, err
}

const getProfilesByUserID = `-- name: GetProfilesByUserID :many
SELECT id, user_id, role, profile_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id, legal_name_th, phone, address_line1, subdistrict, district, province, postal_code, branch_number, legal_name_en FROM profiles WHERE user_id = $1 AND is_active = TRUE ORDER BY created_at ASC
`

func (q *Queries) GetProfilesByUserID(ctx context.Context, userID uuid.UUID) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, getProfilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.ProfileName,
			&i.TaxID,
			&i.IsJuristic,
			&i.IsVatRegistered,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LineID,
			&i.LegalNameTh,
			&i.Phone,
			&i.AddressLine1,
			&i.Subdistrict,
			&i.District,
			&i.Province,
			&i.PostalCode,
			&i.BranchNumber,
			&i.LegalNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles SET
  profile_name   = $2,
  legal_name_th  = $3,
  legal_name_en  = $4,
  phone          = $5,
  address_line1  = $6,
  subdistrict    = $7,
  district       = $8,
  province       = $9,
  postal_code    = $10,
  branch_number  = $11,
  tax_id         = $12,
  is_juristic    = $13,
  is_vat_registered = $14,
  line_id        = $15,
  updated_at     = NOW()
WHERE id = $1
RETURNING id, user_id, role, profile_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id, legal_name_th, phone, address_line1, subdistrict, district, province, postal_code, branch_number, legal_name_en
`

type UpdateProfileParams struct {
	ID              uuid.UUID      `json:"id"`
	ProfileName     string         `json:"profile_name"`
	LegalNameTh     string         `json:"legal_name_th"`
	LegalNameEn     string         `json:"legal_name_en"`
	Phone           string         `json:"phone"`
	AddressLine1    string         `json:"address_line1"`
	Subdistrict     string         `json:"subdistrict"`
	District        string         `json:"district"`
	Province        string         `json:"province"`
	PostalCode      string         `json:"postal_code"`
	BranchNumber    string         `json:"branch_number"`
	TaxID           sql.NullString `json:"tax_id"`
	IsJuristic      bool           `json:"is_juristic"`
	IsVatRegistered bool           `json:"is_vat_registered"`
	LineID          sql.NullString `json:"line_id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.ID,
		arg.ProfileName,
		arg.LegalNameTh,
		arg.LegalNameEn,
		arg.Phone,
		arg.AddressLine1,
		arg.Subdistrict,
		arg.District,
		arg.Province,
		arg.PostalCode,
		arg.BranchNumber,
		arg.TaxID,
		arg.IsJuristic,
		arg.IsVatRegistered,
		arg.LineID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.ProfileName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
		&i.LegalNameTh,
		&i.Phone,
		&i.AddressLine1,
		&i.Subdistrict,
		&i.District,
		&i.Province,
		&i.PostalCode,
		&i.BranchNumber,
		&i.LegalNameEn,
	)
	return i, err
}
