// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, role, display_name)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, display_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id
`

type CreateProfileParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Role        ProfileRole `json:"role"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile, arg.UserID, arg.Role, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, user_id, role, display_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
	)
	return i, err
}

const getProfileByUserAndRole = `-- name: GetProfileByUserAndRole :one
SELECT id, user_id, role, display_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id FROM profiles WHERE user_id = $1 AND role = $2
`

type GetProfileByUserAndRoleParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Role   ProfileRole `json:"role"`
}

func (q *Queries) GetProfileByUserAndRole(ctx context.Context, arg GetProfileByUserAndRoleParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserAndRole, arg.UserID, arg.Role)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
	)
	return i, err
}

const getProfilesByUserID = `-- name: GetProfilesByUserID :many
SELECT id, user_id, role, display_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id FROM profiles WHERE user_id = $1 AND is_active = TRUE ORDER BY created_at ASC
`

func (q *Queries) GetProfilesByUserID(ctx context.Context, userID uuid.UUID) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, getProfilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.DisplayName,
			&i.TaxID,
			&i.IsJuristic,
			&i.IsVatRegistered,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LineID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles SET display_name = $2, line_id = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, role, display_name, tax_id, is_juristic, is_vat_registered, is_active, created_at, updated_at, line_id
`

type UpdateProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	DisplayName string         `json:"display_name"`
	LineID      sql.NullString `json:"line_id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile, arg.ID, arg.DisplayName, arg.LineID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LineID,
	)
	return i, err
}
