// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckOverlappingBookings(ctx context.Context, arg CheckOverlappingBookingsParams) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error)
	GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error)
	GetProfileByUserAndRole(ctx context.Context, arg GetProfileByUserAndRoleParams) (Profile, error)
	GetProfilesByUserID(ctx context.Context, userID uuid.UUID) ([]Profile, error)
	GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListBookingsByRenter(ctx context.Context, renterID uuid.UUID) ([]Booking, error)
	ListBookingsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Booking, error)
	ListSpaces(ctx context.Context) ([]Space, error)
	ListSpacesByCategory(ctx context.Context, category SpaceCategory) ([]Space, error)
	ListSpacesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Space, error)
	SetSpaceActive(ctx context.Context, arg SetSpaceActiveParams) (Space, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error)
}

var _ Querier = (*Queries)(nil)
