// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BulkCompleteConfirmedBookings(ctx context.Context) ([]Booking, error)
	BulkExpirePendingBookings(ctx context.Context) ([]Booking, error)
	CancelOverlappingPendingBookings(ctx context.Context, arg CancelOverlappingPendingBookingsParams) ([]Booking, error)
	CheckOverlappingBookings(ctx context.Context, arg CheckOverlappingBookingsParams) (int64, error)
	CheckOverlappingSpaceBlocks(ctx context.Context, arg CheckOverlappingSpaceBlocksParams) (int64, error)
	CountActiveBookingsByRenterForSpace(ctx context.Context, arg CountActiveBookingsByRenterForSpaceParams) (int64, error)
	CountBookingsBySpace(ctx context.Context, spaceID uuid.UUID) (int64, error)
	CountPendingBookingsByRenter(ctx context.Context, renterID uuid.UUID) (int64, error)
	CountSpaces(ctx context.Context) (int64, error)
	CountSpacesByCategory(ctx context.Context, category SpaceCategory) (int64, error)
	CountSpacesByCategoryExcludeUser(ctx context.Context, arg CountSpacesByCategoryExcludeUserParams) (int64, error)
	CountSpacesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CountSpacesExcludeUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, profileID uuid.UUID) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error)
	CreateSpaceBlock(ctx context.Context, arg CreateSpaceBlockParams) (SpaceBlock, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSpace(ctx context.Context, arg DeleteSpaceParams) error
	DeleteSpaceAvailability(ctx context.Context, spaceID uuid.UUID) error
	DeleteSpaceBlock(ctx context.Context, arg DeleteSpaceBlockParams) error
	GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error)
	GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error)
	GetProfileByUserAndRole(ctx context.Context, arg GetProfileByUserAndRoleParams) (Profile, error)
	GetProfilesByUserID(ctx context.Context, userID uuid.UUID) ([]Profile, error)
	GetSpaceAvailability(ctx context.Context, spaceID uuid.UUID) ([]SpaceAvailability, error)
	GetSpaceBlocksInRange(ctx context.Context, arg GetSpaceBlocksInRangeParams) ([]SpaceBlock, error)
	GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error)
	GetSystemConfig(ctx context.Context, key string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListActiveBookingsInRange(ctx context.Context, arg ListActiveBookingsInRangeParams) ([]Booking, error)
	ListBookingsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Booking, error)
	ListBookingsByOwnerEnriched(ctx context.Context, ownerID uuid.UUID) ([]ListBookingsByOwnerEnrichedRow, error)
	ListPaymentPendingBookings(ctx context.Context) ([]ListPaymentPendingBookingsRow, error)
	ListBookingsByRenter(ctx context.Context, renterID uuid.UUID) ([]Booking, error)
	ListBookingsByRenterEnriched(ctx context.Context, renterID uuid.UUID) ([]ListBookingsByRenterEnrichedRow, error)
	ListBookingsBySpace(ctx context.Context, spaceID uuid.UUID) ([]Booking, error)
	ListBookingsBySpacePaginated(ctx context.Context, arg ListBookingsBySpacePaginatedParams) ([]Booking, error)
	ListNotificationsByProfile(ctx context.Context, arg ListNotificationsByProfileParams) ([]Notification, error)
	ListSpaceBlocksBySpace(ctx context.Context, spaceID uuid.UUID) ([]SpaceBlock, error)
	ListSpaces(ctx context.Context) ([]Space, error)
	ListSpacesByCategory(ctx context.Context, category SpaceCategory) ([]Space, error)
	ListSpacesByCategoryPaginated(ctx context.Context, arg ListSpacesByCategoryPaginatedParams) ([]Space, error)
	ListSpacesByCategoryPaginatedExcludeUser(ctx context.Context, arg ListSpacesByCategoryPaginatedExcludeUserParams) ([]Space, error)
	ListSpacesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Space, error)
	ListSpacesByOwnerPaginated(ctx context.Context, arg ListSpacesByOwnerPaginatedParams) ([]Space, error)
	ListSpacesPaginated(ctx context.Context, arg ListSpacesPaginatedParams) ([]Space, error)
	ListSpacesPaginatedExcludeUser(ctx context.Context, arg ListSpacesPaginatedExcludeUserParams) ([]Space, error)
	MarkAllNotificationsRead(ctx context.Context, profileID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	SetSpaceActive(ctx context.Context, arg SetSpaceActiveParams) (Space, error)
	SupersedeNotificationsByBooking(ctx context.Context, bookingID uuid.UUID) error
	SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) error
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error)
	UpsertSpaceAvailability(ctx context.Context, arg UpsertSpaceAvailabilityParams) (SpaceAvailability, error)
}

var _ Querier = (*Queries)(nil)
