// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, weekend_surcharge_pct)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct
`

type CreateSpaceParams struct {
	OwnerID             uuid.UUID     `json:"owner_id"`
	Name                string        `json:"name"`
	Description         string        `json:"description"`
	Location            string        `json:"location"`
	Category            SpaceCategory `json:"category"`
	Images              []string      `json:"images"`
	HourlyRate          int32         `json:"hourly_rate"`
	DailyRate           int32         `json:"daily_rate"`
	MinHours            int32         `json:"min_hours"`
	Capacity            int32         `json:"capacity"`
	Amenities           []string      `json:"amenities"`
	WeekendSurchargePct int32         `json:"weekend_surcharge_pct"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Category,
		pq.Array(arg.Images),
		arg.HourlyRate,
		arg.DailyRate,
		arg.MinHours,
		arg.Capacity,
		pq.Array(arg.Amenities),
		arg.WeekendSurchargePct,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinHours,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
	)
	return i, err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct FROM spaces
WHERE id = $1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinHours,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
	)
	return i, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct FROM spaces
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListSpaces(ctx context.Context) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinHours,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByCategory = `-- name: ListSpacesByCategory :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct FROM spaces
WHERE is_active = TRUE AND category = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByCategory(ctx context.Context, category SpaceCategory) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinHours,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByOwner = `-- name: ListSpacesByOwner :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct FROM spaces
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinHours,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSpaceActive = `-- name: SetSpaceActive :one
UPDATE spaces SET is_active = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct
`

type SetSpaceActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
	OwnerID  uuid.UUID `json:"owner_id"`
}

func (q *Queries) SetSpaceActive(ctx context.Context, arg SetSpaceActiveParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, setSpaceActive, arg.ID, arg.IsActive, arg.OwnerID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinHours,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
	)
	return i, err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces SET
  name                  = $2,
  description           = $3,
  location              = $4,
  category              = $5,
  images                = $6,
  hourly_rate           = $7,
  daily_rate            = $8,
  min_hours             = $9,
  capacity              = $10,
  amenities             = $11,
  weekend_surcharge_pct = $12,
  updated_at            = NOW()
WHERE id = $1 AND owner_id = $13
RETURNING id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_hours, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct
`

type UpdateSpaceParams struct {
	ID                  uuid.UUID     `json:"id"`
	Name                string        `json:"name"`
	Description         string        `json:"description"`
	Location            string        `json:"location"`
	Category            SpaceCategory `json:"category"`
	Images              []string      `json:"images"`
	HourlyRate          int32         `json:"hourly_rate"`
	DailyRate           int32         `json:"daily_rate"`
	MinHours            int32         `json:"min_hours"`
	Capacity            int32         `json:"capacity"`
	Amenities           []string      `json:"amenities"`
	WeekendSurchargePct int32         `json:"weekend_surcharge_pct"`
	OwnerID             uuid.UUID     `json:"owner_id"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, updateSpace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Category,
		pq.Array(arg.Images),
		arg.HourlyRate,
		arg.DailyRate,
		arg.MinHours,
		arg.Capacity,
		pq.Array(arg.Amenities),
		arg.WeekendSurchargePct,
		arg.OwnerID,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinHours,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
	)
	return i, err
}
