// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countSpaces = `-- name: CountSpaces :one
SELECT COUNT(*) FROM spaces WHERE is_active = TRUE
`

func (q *Queries) CountSpaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpacesByCategory = `-- name: CountSpacesByCategory :one
SELECT COUNT(*) FROM spaces WHERE is_active = TRUE AND category = $1
`

func (q *Queries) CountSpacesByCategory(ctx context.Context, category SpaceCategory) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpacesByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpacesByCategoryExcludeUser = `-- name: CountSpacesByCategoryExcludeUser :one
SELECT COUNT(*) FROM spaces
WHERE is_active = TRUE
  AND category = $1
  AND owner_id NOT IN (SELECT id FROM profiles WHERE user_id = $2)
`

type CountSpacesByCategoryExcludeUserParams struct {
	Category SpaceCategory `json:"category"`
	UserID   uuid.UUID     `json:"user_id"`
}

func (q *Queries) CountSpacesByCategoryExcludeUser(ctx context.Context, arg CountSpacesByCategoryExcludeUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpacesByCategoryExcludeUser, arg.Category, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpacesByOwner = `-- name: CountSpacesByOwner :one
SELECT COUNT(*) FROM spaces WHERE owner_id = $1
`

func (q *Queries) CountSpacesByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpacesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpacesExcludeUser = `-- name: CountSpacesExcludeUser :one
SELECT COUNT(*) FROM spaces
WHERE is_active = TRUE
  AND owner_id NOT IN (SELECT id FROM profiles WHERE user_id = $1)
`

func (q *Queries) CountSpacesExcludeUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpacesExcludeUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, weekend_surcharge_pct)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes
`

type CreateSpaceParams struct {
	OwnerID             uuid.UUID     `json:"owner_id"`
	Name                string        `json:"name"`
	Description         string        `json:"description"`
	Location            string        `json:"location"`
	Category            SpaceCategory `json:"category"`
	Images              []string      `json:"images"`
	HourlyRate          int32         `json:"hourly_rate"`
	DailyRate           int32         `json:"daily_rate"`
	MinMinutes          int32         `json:"min_minutes"`
	Capacity            int32         `json:"capacity"`
	Amenities           []string      `json:"amenities"`
	WeekendSurchargePct int32         `json:"weekend_surcharge_pct"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Category,
		pq.Array(arg.Images),
		arg.HourlyRate,
		arg.DailyRate,
		arg.MinMinutes,
		arg.Capacity,
		pq.Array(arg.Amenities),
		arg.WeekendSurchargePct,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinMinutes,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
		&i.MinNoticeHours,
		&i.MaxBookingMinutes,
		&i.TurnaroundMinutes,
		&i.DepositPct,
		&i.PaymentDeadlineMinutes,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces
WHERE id = $1 AND owner_id = $2
`

type DeleteSpaceParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteSpace(ctx context.Context, arg DeleteSpaceParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpace, arg.ID, arg.OwnerID)
	return err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE id = $1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinMinutes,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
		&i.MinNoticeHours,
		&i.MaxBookingMinutes,
		&i.TurnaroundMinutes,
		&i.DepositPct,
		&i.PaymentDeadlineMinutes,
	)
	return i, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListSpaces(ctx context.Context) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByCategory = `-- name: ListSpacesByCategory :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE is_active = TRUE AND category = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByCategory(ctx context.Context, category SpaceCategory) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByCategoryPaginated = `-- name: ListSpacesByCategoryPaginated :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE is_active = TRUE AND category = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListSpacesByCategoryPaginatedParams struct {
	Category SpaceCategory `json:"category"`
	Off      int32         `json:"off"`
	Lim      int32         `json:"lim"`
}

func (q *Queries) ListSpacesByCategoryPaginated(ctx context.Context, arg ListSpacesByCategoryPaginatedParams) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByCategoryPaginated, arg.Category, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByCategoryPaginatedExcludeUser = `-- name: ListSpacesByCategoryPaginatedExcludeUser :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE is_active = TRUE
  AND category = $1
  AND owner_id NOT IN (SELECT id FROM profiles WHERE user_id = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSpacesByCategoryPaginatedExcludeUserParams struct {
	Category SpaceCategory `json:"category"`
	UserID   uuid.UUID     `json:"user_id"`
	Off      int32         `json:"off"`
	Lim      int32         `json:"lim"`
}

func (q *Queries) ListSpacesByCategoryPaginatedExcludeUser(ctx context.Context, arg ListSpacesByCategoryPaginatedExcludeUserParams) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByCategoryPaginatedExcludeUser,
		arg.Category,
		arg.UserID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByOwner = `-- name: ListSpacesByOwner :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByOwner(ctx context.Context, ownerID uuid.UUID) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByOwnerPaginated = `-- name: ListSpacesByOwnerPaginated :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSpacesByOwnerPaginatedParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListSpacesByOwnerPaginated(ctx context.Context, arg ListSpacesByOwnerPaginatedParams) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesByOwnerPaginated, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesPaginated = `-- name: ListSpacesPaginated :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSpacesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSpacesPaginated(ctx context.Context, arg ListSpacesPaginatedParams) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesPaginatedExcludeUser = `-- name: ListSpacesPaginatedExcludeUser :many
SELECT id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes FROM spaces
WHERE is_active = TRUE
  AND owner_id NOT IN (SELECT id FROM profiles WHERE user_id = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSpacesPaginatedExcludeUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListSpacesPaginatedExcludeUser(ctx context.Context, arg ListSpacesPaginatedExcludeUserParams) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpacesPaginatedExcludeUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.Category,
			pq.Array(&i.Images),
			&i.HourlyRate,
			&i.DailyRate,
			&i.MinMinutes,
			&i.Capacity,
			pq.Array(&i.Amenities),
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WeekendSurchargePct,
			&i.MinNoticeHours,
			&i.MaxBookingMinutes,
			&i.TurnaroundMinutes,
			&i.DepositPct,
			&i.PaymentDeadlineMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSpaceActive = `-- name: SetSpaceActive :one
UPDATE spaces SET is_active = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes
`

type SetSpaceActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
	OwnerID  uuid.UUID `json:"owner_id"`
}

func (q *Queries) SetSpaceActive(ctx context.Context, arg SetSpaceActiveParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, setSpaceActive, arg.ID, arg.IsActive, arg.OwnerID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinMinutes,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
		&i.MinNoticeHours,
		&i.MaxBookingMinutes,
		&i.TurnaroundMinutes,
		&i.DepositPct,
		&i.PaymentDeadlineMinutes,
	)
	return i, err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces SET
  name                  = $2,
  description           = $3,
  location              = $4,
  category              = $5,
  images                = $6,
  hourly_rate           = $7,
  daily_rate            = $8,
  min_minutes           = $9,
  capacity              = $10,
  amenities             = $11,
  weekend_surcharge_pct = $12,
  updated_at            = NOW()
WHERE id = $1 AND owner_id = $13
RETURNING id, owner_id, name, description, location, category, images, hourly_rate, daily_rate, min_minutes, capacity, amenities, is_active, created_at, updated_at, weekend_surcharge_pct, min_notice_hours, max_booking_minutes, turnaround_minutes, deposit_pct, payment_deadline_minutes
`

type UpdateSpaceParams struct {
	ID                  uuid.UUID     `json:"id"`
	Name                string        `json:"name"`
	Description         string        `json:"description"`
	Location            string        `json:"location"`
	Category            SpaceCategory `json:"category"`
	Images              []string      `json:"images"`
	HourlyRate          int32         `json:"hourly_rate"`
	DailyRate           int32         `json:"daily_rate"`
	MinMinutes          int32         `json:"min_minutes"`
	Capacity            int32         `json:"capacity"`
	Amenities           []string      `json:"amenities"`
	WeekendSurchargePct int32         `json:"weekend_surcharge_pct"`
	OwnerID             uuid.UUID     `json:"owner_id"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, updateSpace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.Category,
		pq.Array(arg.Images),
		arg.HourlyRate,
		arg.DailyRate,
		arg.MinMinutes,
		arg.Capacity,
		pq.Array(arg.Amenities),
		arg.WeekendSurchargePct,
		arg.OwnerID,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.Category,
		pq.Array(&i.Images),
		&i.HourlyRate,
		&i.DailyRate,
		&i.MinMinutes,
		&i.Capacity,
		pq.Array(&i.Amenities),
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WeekendSurchargePct,
		&i.MinNoticeHours,
		&i.MaxBookingMinutes,
		&i.TurnaroundMinutes,
		&i.DepositPct,
		&i.PaymentDeadlineMinutes,
	)
	return i, err
}
