// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: space_blocks.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkOverlappingSpaceBlocks = `-- name: CheckOverlappingSpaceBlocks :one
SELECT COUNT(*) FROM space_blocks
WHERE space_id   = $1
  AND start_time < $3
  AND end_time   > $2
`

type CheckOverlappingSpaceBlocksParams struct {
	SpaceID   uuid.UUID `json:"space_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) CheckOverlappingSpaceBlocks(ctx context.Context, arg CheckOverlappingSpaceBlocksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkOverlappingSpaceBlocks, arg.SpaceID, arg.EndTime, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpaceBlock = `-- name: CreateSpaceBlock :one
INSERT INTO space_blocks (space_id, start_time, end_time, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, space_id, start_time, end_time, reason, created_at
`

type CreateSpaceBlockParams struct {
	SpaceID   uuid.UUID      `json:"space_id"`
	StartTime time.Time      `json:"start_time"`
	EndTime   time.Time      `json:"end_time"`
	Reason    sql.NullString `json:"reason"`
}

func (q *Queries) CreateSpaceBlock(ctx context.Context, arg CreateSpaceBlockParams) (SpaceBlock, error) {
	row := q.db.QueryRowContext(ctx, createSpaceBlock,
		arg.SpaceID,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i SpaceBlock
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSpaceBlock = `-- name: DeleteSpaceBlock :exec
DELETE FROM space_blocks WHERE id = $1 AND space_id = $2
`

type DeleteSpaceBlockParams struct {
	ID      uuid.UUID `json:"id"`
	SpaceID uuid.UUID `json:"space_id"`
}

func (q *Queries) DeleteSpaceBlock(ctx context.Context, arg DeleteSpaceBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpaceBlock, arg.ID, arg.SpaceID)
	return err
}

const getSpaceBlocksInRange = `-- name: GetSpaceBlocksInRange :many
SELECT id, space_id, start_time, end_time, reason, created_at FROM space_blocks
WHERE space_id   = $1
  AND start_time < $3
  AND end_time   > $2
ORDER BY start_time ASC
`

type GetSpaceBlocksInRangeParams struct {
	SpaceID   uuid.UUID `json:"space_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) GetSpaceBlocksInRange(ctx context.Context, arg GetSpaceBlocksInRangeParams) ([]SpaceBlock, error) {
	rows, err := q.db.QueryContext(ctx, getSpaceBlocksInRange, arg.SpaceID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceBlock
	for rows.Next() {
		var i SpaceBlock
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceBlocksBySpace = `-- name: ListSpaceBlocksBySpace :many
SELECT id, space_id, start_time, end_time, reason, created_at FROM space_blocks
WHERE space_id = $1
ORDER BY start_time ASC
`

func (q *Queries) ListSpaceBlocksBySpace(ctx context.Context, spaceID uuid.UUID) ([]SpaceBlock, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceBlocksBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceBlock
	for rows.Next() {
		var i SpaceBlock
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
