// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_config.sql

package store

import (
	"context"
)

const getSystemConfig = `-- name: GetSystemConfig :one
SELECT value FROM system_config WHERE key = $1
`

func (q *Queries) GetSystemConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSystemConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setSystemConfig = `-- name: SetSystemConfig :exec
INSERT INTO system_config (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type SetSystemConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) error {
	_, err := q.db.ExecContext(ctx, setSystemConfig, arg.Key, arg.Value)
	return err
}
