// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, phone, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, full_name, phone, role, tax_id, is_juristic, is_vat_registered, created_at, updated_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	Phone        sql.NullString `json:"phone"`
	Role         UserRole       `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, phone, role, tax_id, is_juristic, is_vat_registered, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, phone, role, tax_id, is_juristic, is_vat_registered, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTaxProfile = `-- name: UpdateUserTaxProfile :one
UPDATE users SET
  tax_id            = $2,
  is_juristic       = $3,
  is_vat_registered = $4,
  updated_at        = NOW()
WHERE id = $1
RETURNING id, email, password_hash, full_name, phone, role, tax_id, is_juristic, is_vat_registered, created_at, updated_at
`

type UpdateUserTaxProfileParams struct {
	ID              uuid.UUID      `json:"id"`
	TaxID           sql.NullString `json:"tax_id"`
	IsJuristic      bool           `json:"is_juristic"`
	IsVatRegistered bool           `json:"is_vat_registered"`
}

func (q *Queries) UpdateUserTaxProfile(ctx context.Context, arg UpdateUserTaxProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserTaxProfile,
		arg.ID,
		arg.TaxID,
		arg.IsJuristic,
		arg.IsVatRegistered,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.TaxID,
		&i.IsJuristic,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
